### ISSUE TITLE
Use another distribution medium for the wiki model

### ISSUE THREAD

**Issue by dedcode** [idio/wiki2vec#10]
Hi,
Can you please consider moving the model to another file repository? 
May be the new Github large files fs. or dropbox.
Torrent is extremely slow.
Thanks!

**Comment by dav009** [comment]
I'm going to make them available via http://datahub.io/

**Comment by dedcode** [comment]
:+1: 
Fyi, I was finally able to download relatively faster at home. From the university it was announcing 1 week :)

**Comment by keynmol** [comment]
Closing this as @dedcode managed to download the model after all.

We'll think about a better data sharing platform.
