### ISSUE TITLE
Question about <WINDOW_SIZE>

### ISSUE THREAD

**Issue by zhq2009** [idio/wiki2vec#33]
Hello,

In the command you mentioned wiki2vec.sh pathToCorpus pathToOutputFile <MIN_WORD_COUNT> <VECTOR_SIZE> <WINDOW_SIZE>, what's the <WINDOW_SIZE> represent for?

In terms of training data, is it using CBOW, Skip-gram or log-linear?

Thank you

**Comment by keynmol** [comment]
Hello!

Those parameters are passed directly to gensim's implementation of word2vec. Please refer to the [documentation](https://radimrehurek.com/gensim/models/word2vec.html) for the meaning of the parameters as well as the default algorithm.

Short answer: 1) <WINDOW_SIZE> is "the maximum distance between the current and predicted word within a sentence." 2) default algorithm is CBOW

**Comment by zhq2009** [comment]
Thank you

When I looked at the code in gensim_word2vec.py

    model = gensim.models.Word2Vec(sentences, min_count=min_count, size=size,
                                   window=window, sg=1, workers=workers)

For sg=1, is it meaning I am currently training with Skip-Gram?

Thank you very much.

**Comment by keynmol** [comment]
Yeah, sorry, misread the documentation. It's skip-gram after all.
