### ISSUE TITLE
Issue with Download Link for prebuilt word2vec models

### ISSUE THREAD

**Issue by apogre** [idio/wiki2vec#34]
https://github.com/idio/wiki2vec/raw/master/torrents/enwiki-gensim-word2vec-1000-nostem-10cbow.torrent
Torrent Not Found!
Any other sources than torrent download?

**Comment by keynmol** [comment]
Hi, I clicked on the link you put in the issue and started the download without any problem at 1.8 MB/s. There's also an alternative location for the torrent: http://academictorrents.com/details/5d18911e7036870197bf5e23cf1be96d3353518a

Unfortunately at the moment torrenting is the only viable option for us to share files this big.

**Comment by tgalery** [comment]
@apogre if you are happy with this, we are closing the issue.
